---
- hosts: nodo1
  become: yes
  tasks:
  - name: Install bind9
    apt:
      name: bind9
      update_cache: yes
   
  - name: Install mysql
    apt:
     name: mysql-server
     update_cache: yes

  - name: Config named.conf.local
    template:
      src: named.j2
      dest: /var/cache/bind/named.conf.local

  - name: Config 10.0.0 zone
    template:
      src: 10.0.0.j2
      dest: /var/cache/bind/db.10.0.0

  handlers:
    - name: Restart bind9
      service: 
        name: bind9
        state: restarted