---
- hosts: nodo1
  become: yes
  vars:
    zone: example.com
    server_name: example.com
    server_hostname: example.com

    server: wordpress
    nodo1: 10.0.0.11
    nodo2: 10.0.0.12
    ext_nodo1: 192.168.1.11
    ext_nodo2: 192.168.1.12

    wp_db_name: 'wordpress'
    wp_db_user: wordpress
    wp_db_password: password

    mysql_port: 3306
    wp_version: "4.9.2"

    wp_core_url: http://wordpress.example.com
    wp_core_title:  Ansible
    wp_core_admin_user: admin
    wp_core_admin_pass: admin
    wp_core_admin_mail: admin@example.com
    wp_db_host: "{{ nodo1 }}"
  tasks:
  - name: Install bind9
    apt:
      name: bind9
      update_cache: yes
   
  - name: Install mysql
    apt:
     name:  mysql-server
     update_cache: yes

  - name: Install python-mysqldb
    apt:
      name: python-mysqldb
  - name: Set root user password
    become: true
    become_user: root
    mysql_user:
      name: root
      host: "{{ item }}"
      password: root
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
  
  - name: copy .my.cnf file with root password credentials
    become: true
    become_user: root
    template:
      src: .my.cnf 
      dest: /root/.my.cnf 
      owner: root 
      mode: 0600

  - name: copy 50-server configuration - enable remote connections
    become: true
    copy: 
      src: 50-server.cnf 
      dest: /etc/mysql/mariadb.conf.d/50-server.cnf


  - name: Create WordPress database
    become: true
    mysql_db: 
      name: "{{ wp_db_name }}" 
      state: present

  - name: create mariadb user
    become: true
    become_user: root
    mysql_user:
      name: "{{ wp_db_user }}"
      host: "{{ item }}"
      password: "{{ wp_db_password }}"
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - "{{ nodo2 }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: Config named.conf.local
    template:
      src: named.j2
      dest: /var/cache/bind/named.conf.local

  - name: Config example.com zone
    template:
      src: example.com.conf
      dest: /var/cache/bind/db.example.com.conf

  handlers:
    - name: Restart bind9
      service: 
        name: bind9
        state: restarted

    - name: Restart mariadb
      service: 
        name: mysql
        state: restarted
        become: yes
