---
- hosts: nodo1
  become: yes

  vars:
    zone: "example.com"
    server: "wordpress"
    nodo2: "10.0.0.12"

  tasks:
  - name: Install bind9
    apt:
      name: bind9
      update_cache: yes
   
  - name: Install mysql
    apt:
     name: mysql-server
     update_cache: yes

  - name: Config named.conf.local
    template:
      src: named.j2
      dest: /var/cache/bind/named.conf.local

  - name: Config 10.0.0 zone
    template:
      src: 10.0.0.j2
      dest: /var/cache/bind/db.10.0.0.conf

  - name: Config example.com zone
    template:
      src: example.com.j2
      dest: /var/cache/bind/example.com.conf

  handlers:
    - name: Restart bind9
      service: 
        name: bind9
        state: restarted