- hosts: nodo2
  become: yes
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      update_cache: yes

  - name: Install FPM
    apt:
      name: php7.0-fpm
      update_cache: yes
          
  - name: Unzip WordPress
    unarchive:
        src: wordpress.zip 
        dest: /vagrant/
  
  - name: Symlink web root to unzipped WordPress
    file:
      src: "/vagrant/wordpress"
      dest: "/var/www/wordpress"
      state: "link"

  - name: Delete default site
    file:
      path: /etc/nginx/sites-availables/default
      state: absent

  
