---
- hosts: nodo2
  become: yes
  vars:
    wp_version: "4.9.2"
    server_name: "example.com"
   
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      update_cache: yes

  - name: Install FPM
    apt:
      name: php7.0-fpm
      update_cache: yes
          
  - name: Download WordPress
    get_url: 
      url: http://wordpress.org/wordpress-{{ wp_version }}.tar.gz 
      dest: /home/vagrant/wordpress-{{ wp_version }}.tar.gz

  - name: Extract archive
    command: /bin/tar xvf wordpress-{{ wp_version }}.tar.gz 
    args:  
      chdir: /var/www/html/
      creates: /var/www/html/wordpress


  - name: Delete default site
    file:
      path: /etc/nginx/sites-availables/default
      state: absent
  
  - name: Copy nginx configuration for wordpress
    template: 
        src: default.conf
        dest: /etc/nginx/conf.d/default.conf

  handlers:
    - name: Restart nginx
      service: 
        name: nginx
        state: restarted

    - name: Restart fpm
      service: 
        name: php7.0-fpm
        state: restarted
