---
- hosts: nodo2
  become: yes
  vars:
    wp_version: "4.9.2"
    server_name: "example.com"
    wp_db_name: wordpress 
    wp_db_user: wordpress
    wp_db_password: password
    mysql_port: 3306
    server_hostname: example.com
    nodo2: 10.0.0.12
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      update_cache: yes

  - name: Install FPM
    apt: 
      name: "{{ item }}"
    with_items:
      - php7.0
      - php7.0-fpm
      - php7.0-mysql
          
  - name: Download WordPress
    become: yes
    unarchive:
      src: http://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes

  - name: Add group "wordpress"
    group: 
      name: wordpress

  - name: Add user "wordpress"
    user:   
      name: wordpress 
      group: wordpress 
      home: /var/www/html/wordpress/

  - name: Fetch random salts for WordPress config
    local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
    register: "wp_salt"
    become: no
    become_method: sudo

  - name: Create WordPress database
    mysql_db: 
      name: "{{ wp_db_name }}" 
      state: present

  - name: Create WordPress database user
    become: true
    become_user: root
    mysql_user:
      name: "{{ wp_db_user }}"
      host: "{{ item }}"
      password: "{{ wp_db_password }}"
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - "{{ nodo2 }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: Copy WordPress config file
    template: src=wp-config.php dest=/var/www/html/wordpress/wp-config.php

  - name: Change ownership of WordPress installation
    file: path=/var/www/html/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes setype=httpd_sys_content_t

  - name: Start php-fpm Service
    service: name=php7.0-fpm state=started enabled=yes

  - name: Delete default site
    file:
      path: /etc/nginx/sites-availables/default
      state: absent
  
  - name: Copy nginx configuration for wordpress
    template: 
        src: default
        dest: /etc/nginx/sites-enabled/default

  handlers:
    - name: Restart nginx
      service: 
        name: nginx
        state: restarted

    - name: Restart fpm
      service: 
        name: php7.0-fpm
        state: restarted
